"""empty message

Revision ID: a8fe1593d7fe
Revises: a2b86c1c6fa2
Create Date: 2022-11-21 12:39:44.328246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fe1593d7fe'
down_revision = 'a2b86c1c6fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=10), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('client_phone', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
